"""
Downloads ASPM Airport Analysis reports (Display: Analysis - All Flights)
as MS Excel files, one calendar month at a time, for all airports
(leaving airport selection empty = "All airports" in ASPM).

The ASPM Airport Analysis form (https://www.aspm.faa.gov/apm/sys/AnalysisAP.asp)
is a legacy classic-ASP page with no stable query-string API: selections are
tracked in server-side session state and the final report is generated by a
JS-computed form POST to apm-server-x.asp. Reliable automation requires
driving the actual page (Playwright) rather than replaying raw HTTP requests.

Session bootstrap matters: navigating directly to AnalysisAP.asp redirects to
the ASPM homepage (referrer/session check). The working path is:
  aspm.faa.gov/ -> click "Aviation System Performance Metrics" -> click "Airport Analysis"

Grouping fields (Airport / Date / Local Hour / GMT Hour) are added by calling
the page's own JS functions (addFld / addHR / addGMTHR) directly, which is
more reliable than clicking the small "Add" icon links.

Usage:
  python download_aspm_airport_analysis.py --start 2016-01 --end 2026-01
  python download_aspm_airport_analysis.py --start 2016-01 --end 2016-01 --headed
"""

import argparse
import calendar
import sys
import time
from pathlib import Path

from playwright.sync_api import sync_playwright, TimeoutError as PWTimeoutError

BASE = "https://www.aspm.faa.gov"
REPORT_TIMEOUT_MS = 180_000  # large legacy-ASP reports can take a while to generate


def month_range(start_year, start_month, end_year, end_month):
    y, m = start_year, start_month
    while (y, m) <= (end_year, end_month):
        yield y, m
        m += 1
        if m > 12:
            m = 1
            y += 1


def open_airport_analysis(page):
    """Click through from the ASPM homepage to the Airport Analysis form.
    Navigating straight to AnalysisAP.asp redirects (referrer/session check)."""
    page.goto(f"{BASE}/", wait_until="domcontentloaded", timeout=120_000)
    page.click("a:has-text('Aviation System Performance Metrics')", timeout=120_000, no_wait_after=True)
    page.wait_for_load_state("domcontentloaded", timeout=120_000)
    page.click("a:has-text('Airport Analysis')", timeout=120_000, no_wait_after=True)
    page.wait_for_load_state("domcontentloaded", timeout=120_000)
    page.wait_for_selector("#MonthsOption", state="attached", timeout=60_000)


def configure_form(page, year, month, include_early_flights=True, reptype="r1"):
    # Several panels (Dates/Output/Filters) are hidden until a left-nav button
    # is clicked via switcher(). checkForm() reads raw DOM state at submit
    # time regardless of visibility, so we set fields directly via JS instead
    # of relying on Playwright's visibility-gated .check()/.select_option().
    #
    # Date type must be "Range" (dtype=r), not "Months" (dtype=m): the
    # Months option internally uses dfld='yyyymm', which aggregates all rows
    # for the month down to one row per airport/hour (~1,840 rows/month).
    # Range uses dfld='yyyymmdd', giving true daily x hourly granularity
    # (~50,000 rows/month) matching what the manual UI downloads produce.
    ym = f"{month:02d}"
    yy = str(year)
    last_day = calendar.monthrange(year, month)[1]
    fd = "01"
    td = f"{last_day:02d}"
    page.evaluate(
        """([ym, yy, fd, td, reptype]) => {
            document.getElementById('RangeOption').checked = true;
            document.querySelector("select[name='fm_r']").value = ym;
            document.querySelector("select[name='fd_r']").value = fd;
            document.querySelector("select[name='fy_r']").value = yy;
            document.querySelector("select[name='tm_r']").value = ym;
            document.querySelector("select[name='td_r']").value = td;
            document.querySelector("select[name='ty_r']").value = yy;
            // rdaytype=all is the default

            // Display: r1=All Flights, r5=EDCT Report (GDP proxy: EDCT is
            // assigned specifically when a flight is caught in a Ground
            // Delay Program), etc.
            document.querySelector(`input[name='reptype'][value='${reptype}']`).checked = true;

            // Format: MS Excel
            document.querySelector("input[name='reportformat'][value='msexcel']").checked = true;
            // nosubtot is checked by default
        }""",
        [ym, yy, fd, td, reptype],
    )

    # Grouping: Airport, Date, Local Hour, GMT Hour
    page.evaluate("addFld('LOCID')")
    page.evaluate("addFld('DATE')")
    page.evaluate("addHR('HR_LOCAL')")
    page.evaluate("addGMTHR('HR_GMT')")

    # Filters
    if include_early_flights:
        page.evaluate("document.querySelector(\"input[name='early']\").checked = true;")
    # oagptm=ptm (Use Flight Plan) is the default; leave as-is
    # hrfrom/hrto left at "Any"; usedep left checked (default)

    # Airport selection left empty -> "All airports" per the form's own placeholder text


def run_and_download(page, context, out_path):
    # Despite target="_blank" on the form, Playwright/Chromium fires the
    # "download" event on the ORIGINATING page, not on a new popup page
    # (confirmed via network tracing: Chrome briefly opens an empty tab for
    # the download and closes it immediately, but the download event is
    # attributed to `page` itself). Listening on context "page" events for
    # a new page's download misses it entirely.
    downloads = []
    page.on("download", lambda d: downloads.append(d))

    page.click("#b_Submit a")

    deadline = time.time() + REPORT_TIMEOUT_MS / 1000
    while not downloads and time.time() < deadline:
        page.wait_for_timeout(250)
    if not downloads:
        raise TimeoutError("no download event observed")

    downloads[0].save_as(str(out_path))


MIN_VALID_SIZE = 5_000_000  # real monthly reports are ~30-40MB; a genuine
# ASPM/IIS error page (e.g. "An error occurred on the server...") saves as a
# few hundred bytes with a real HTTP 200, so a naive `size > 0` check treats
# it as a successful download. Verified: a real corrupted download was only
# 273 bytes. Anything under this threshold is treated as a failure.


def download_month(playwright, year, month, out_dir, headed=False, reptype="r1"):
    # ASPM's "MS Excel" format is actually an HTML table served with a .xls
    # filename/content-type (verified: file starts with "<!-- --><html>...").
    # Read it with pandas.read_html(), not openpyxl.
    dest = out_dir / f"{year}_{month:02d}.xls"
    if dest.exists() and dest.stat().st_size >= MIN_VALID_SIZE:
        print(f"[skip] {year}-{month:02d} already downloaded")
        return True
    if dest.exists():
        print(f"[warn] {year}-{month:02d} existing file too small ({dest.stat().st_size:,} bytes) - re-downloading")
        dest.unlink()

    browser = playwright.chromium.launch(headless=not headed)
    context = browser.new_context(accept_downloads=True)
    page = context.new_page()
    try:
        open_airport_analysis(page)
        configure_form(page, year, month, reptype=reptype)
        run_and_download(page, context, dest)
        size = dest.stat().st_size
        if size < MIN_VALID_SIZE:
            snippet = dest.read_text(errors="replace")[:200]
            dest.unlink()
            raise ValueError(f"downloaded file too small ({size:,} bytes) - likely a server error page: {snippet!r}")
        print(f"[ok]   {year}-{month:02d} downloaded ({size:,} bytes)")
        return True
    except PWTimeoutError as exc:
        print(f"[fail] {year}-{month:02d} timed out: {exc}")
        return False
    except Exception as exc:
        print(f"[fail] {year}-{month:02d} error: {exc}")
        return False
    finally:
        context.close()
        browser.close()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--start", default="2016-01", help="YYYY-MM")
    parser.add_argument("--end", default="2026-01", help="YYYY-MM")
    parser.add_argument(
        "--reptype",
        default="r1",
        choices=["r1", "r2", "r5", "r6"],
        help="r1=All Flights, r2=Delayed Flights, r5=EDCT Report, r6=EDCT Compliance Report",
    )
    parser.add_argument(
        "--out",
        default=None,
        help="output dir (default: data/aspm_airport_analysis, or data/aspm_edct_report for --reptype r5)",
    )
    parser.add_argument("--headed", action="store_true", help="show the browser window")
    args = parser.parse_args()

    start_year, start_month = (int(x) for x in args.start.split("-"))
    end_year, end_month = (int(x) for x in args.end.split("-"))

    if args.out:
        out_dir = Path(args.out)
    else:
        default_names = {"r1": "aspm_airport_analysis", "r2": "aspm_delayed_flights",
                          "r5": "aspm_edct_report", "r6": "aspm_edct_compliance"}
        out_dir = Path(__file__).resolve().parent.parent / "data" / default_names[args.reptype]
    out_dir.mkdir(parents=True, exist_ok=True)

    months = list(month_range(start_year, start_month, end_year, end_month))
    print(f"Downloading {len(months)} months ({args.reptype}): {args.start} -> {args.end}\n")

    failures = []
    with sync_playwright() as p:
        for i, (year, month) in enumerate(months, start=1):
            print(f"--- [{i}/{len(months)}] {year}-{month:02d} ---")
            ok = download_month(p, year, month, out_dir, headed=args.headed, reptype=args.reptype)
            if not ok:
                failures.append((year, month))
            time.sleep(2)

    print("\nDone.")
    if failures:
        print(f"{len(failures)} month(s) failed: {failures}")
    print(f"Files written to: {out_dir}")


if __name__ == "__main__":
    sys.exit(main())
